# Instructions for Docker Deployment https://confluence.atlassian.com/bitbucket/deploy-to-amazon-ecs-892623902.html
# TODO: Add branch workflows
image: node:10.0.0
options:
  docker: true

pipelines:
  default:
    - step:
        name: build and publish docker image.
        services:
          - docker
        script:
          # Docker variables
          - export IMAGE_NAME="${DOCKER_HUB_USERNAME}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BUILD_NUMBER}"
          # build and test the Node app
          - npm install
          - npm test
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME .
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
  branches:
    master:
    - step:
        services:
          - docker
        script:
          - npm install
    develop:
    - step:
        services:
          - docker
        script:
          - npm install
    release-*:
    - step:
        services:
          - docker
        script:
          - npm install
